### ISSUE TITLE
Issue with setup (AttributeError: 'int' object has no attribute 'split')

### ISSUE THREAD

**Issue by Fenir8** [stevenleeg/geemusic#105]
Hello! I have set up a heroku instance and I'm not quite sure what I've done wrong at this point. I have followed the setup for the alexa skill up to the service simulator testing step, which unfortunately just returns "There was an error calling the remote endpoint, which returned HTTP 500 : INTERNAL SERVER ERROR."

After correcting what seem to be typical errors by going through previous issues etc (removing a trailing slash from my APP_URL variable, obtaining an app password as my account uses two factor authentication, etc), this is what the log from heroku seems to be spitting out when amazon runs it's test.  What am I doing wrong?

2017-07-08T21:00:26.239084+00:00 heroku[router]: at=info method=POST path="/alexa" host=[censored-heroku-address-here] request_id=2419a19b-4437-4dd1-8ef0-3603973811af fwd="72.21.217.155" dyno=web.1 connect=1ms service=45ms status=500 bytes=24228 protocol=https
2017-07-08T21:00:26.237926+00:00 app[web.1]: 10.169.124.243 - - [08/Jul/2017 21:00:26] "POST /alexa HTTP/1.1" 500 -
2017-07-08T21:00:26.238244+00:00 app[web.1]: Traceback (most recent call last):
2017-07-08T21:00:26.238246+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
2017-07-08T21:00:26.238247+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2017-07-08T21:00:26.238248+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
2017-07-08T21:00:26.238248+00:00 app[web.1]:     response = self.handle_exception(e)
2017-07-08T21:00:26.238249+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
2017-07-08T21:00:26.238250+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-07-08T21:00:26.238250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-07-08T21:00:26.238251+00:00 app[web.1]:     raise value
2017-07-08T21:00:26.238252+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-07-08T21:00:26.238252+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-07-08T21:00:26.238253+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-07-08T21:00:26.238254+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-07-08T21:00:26.238254+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-07-08T21:00:26.238255+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-07-08T21:00:26.238256+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-07-08T21:00:26.238256+00:00 app[web.1]:     raise value
2017-07-08T21:00:26.238257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-07-08T21:00:26.238257+00:00 app[web.1]:     rv = self.dispatch_request()
2017-07-08T21:00:26.238258+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-07-08T21:00:26.238259+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-07-08T21:00:26.238259+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 530, in _flask_view_func
2017-07-08T21:00:26.238260+00:00 app[web.1]:     ask_payload = self._alexa_request(verify=self.ask_verify_requests)
2017-07-08T21:00:26.238261+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 492, in _alexa_request
2017-07-08T21:00:26.238261+00:00 app[web.1]:     timestamp = aniso8601.parse_datetime(alexa_request_payload['request']['timestamp'])
2017-07-08T21:00:26.238262+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/aniso8601/time.py", line 120, in parse_datetime
2017-07-08T21:00:26.238262+00:00 app[web.1]:     isodatestr, isotimestr = isodatetimestr.split(delimiter)
2017-07-08T21:00:26.238263+00:00 app[web.1]: AttributeError: 'int' object has no attribute 'split'
2017-07-08T21:00:36.804184+00:00 heroku[router]: at=info method=POST path="/alexa" host=[censored-heroku-address-here] request_id=d09cf1ff-7e7c-470e-999a-26af2c55f7be fwd="72.21.217.162" dyno=web.1 connect=0ms service=59ms status=500 bytes=24228 protocol=https
2017-07-08T21:00:36.806196+00:00 app[web.1]: 10.179.204.228 - - [08/Jul/2017 21:00:36] "POST /alexa HTTP/1.1" 500 -
2017-07-08T21:00:36.806212+00:00 app[web.1]: Traceback (most recent call last):
2017-07-08T21:00:36.806214+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
2017-07-08T21:00:36.806215+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2017-07-08T21:00:36.806216+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
2017-07-08T21:00:36.806216+00:00 app[web.1]:     response = self.handle_exception(e)
2017-07-08T21:00:36.806218+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
2017-07-08T21:00:36.806219+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-07-08T21:00:36.806219+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-07-08T21:00:36.806220+00:00 app[web.1]:     raise value
2017-07-08T21:00:36.806221+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-07-08T21:00:36.806222+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-07-08T21:00:36.806223+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-07-08T21:00:36.806223+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-07-08T21:00:36.806224+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-07-08T21:00:36.806242+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-07-08T21:00:36.806243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-07-08T21:00:36.806243+00:00 app[web.1]:     raise value
2017-07-08T21:00:36.806244+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-07-08T21:00:36.806245+00:00 app[web.1]:     rv = self.dispatch_request()
2017-07-08T21:00:36.806245+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-07-08T21:00:36.806246+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-07-08T21:00:36.806247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 530, in _flask_view_func
2017-07-08T21:00:36.806248+00:00 app[web.1]:     ask_payload = self._alexa_request(verify=self.ask_verify_requests)
2017-07-08T21:00:36.806248+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 492, in _alexa_request
2017-07-08T21:00:36.806249+00:00 app[web.1]:     timestamp = aniso8601.parse_datetime(alexa_request_payload['request']['timestamp'])
2017-07-08T21:00:36.806250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/aniso8601/time.py", line 120, in parse_datetime
2017-07-08T21:00:36.806251+00:00 app[web.1]:     isodatestr, isotimestr = isodatetimestr.split(delimiter)
2017-07-08T21:00:36.806251+00:00 app[web.1]: AttributeError: 'int' object has no attribute 'split'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-07-08T21:00:36.806244+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-07-08T21:00:36.806245+00:00 app[web.1]:     rv = self.dispatch_request()
2017-07-08T21:00:36.806245+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-07-08T21:00:36.806246+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-07-08T21:00:36.806247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 530, in _flask_view_func
2017-07-08T21:00:36.806248+00:00 app[web.1]:     ask_payload = self._alexa_request(verify=self.ask_verify_requests)
2017-07-08T21:00:36.806248+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 492, in _alexa_request
2017-07-08T21:00:36.806249+00:00 app[web.1]:     timestamp = aniso8601.parse_datetime(alexa_request_payload['request']['timestamp'])
2017-07-08T21:00:36.806250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/aniso8601/time.py", line 120, in parse_datetime
2017-07-08T21:00:36.806251+00:00 app[web.1]:     isodatestr, isotimestr = isodatetimestr.split(delimiter)
2017-07-08T21:00:36.806251+00:00 app[web.1]: AttributeError: 'int' object has no attribute 'split'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...

**Comment by Fenir8** [comment]
Oddly, i can "tell geemusic to play x" via echosim and it seems to be working.. wonder what's going on here then.

**Comment by Str8AWay** [comment]
This is amazon being dumb and not following their own specifications for the service simulator.

**Comment by lbarnard** [comment]
I'm also getting this error - is this something that Amazon have changed and that will need fixing in geemusic?

**Comment by Str8AWay** [comment]
No I don't think so. Here is the [issue](https://github.com/johnwheeler/flask-ask/issues/152) for flask-ask where this exception is being thrown.

**Comment by anarinya** [comment]
It sounds like the issue is related to the fact that Amazon's own testing tool expects a different date format than the Echo actually uses. The linked issue @Str8AWay posted has a way to get around this. It's really just the testing tool itself that has a problem, rather than gee music. If you paste 'help' into the 'text/enter utterance' area test, it'll come back and show you some JSON for both the request and response. Copy the request JSON, flip over to the 'JSON' tab instead of text, and paste in the JSON. This'll allow your test to run successfully.

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
