### ISSUE TITLE
Help with Troubleshooting link from Heroku install

### ISSUE THREAD

**Issue by jeffko77** [stevenleeg/geemusic#11]
Hello, 
I have geemusic setup and running on Heroku, and i can ask Alexa to play a song, but no music actually starts playing.  I don't know where to begin troubleshooting. It 
Interaction:
Me: Alexa, tell geemusic to play the song with or without you
Alexa: Playing the song With or Without you by U2.
Alexa: <no music plays>

It seems like it is doing the lookup, but the streaming isn't kicking off.

Heroku instructions followed, Alexa skill test succeeds.

logs from Heroku

2017-01-02T15:56:46.236184+00:00 heroku[router]: at=info method=POST path="/alexa" host=whispering-depths-44089.herokuapp.com request_id=a665335e-163c-43ff-9989-b209a62c43d3 fwd="72.21.217.176" dyno=web.1 connect=1ms service=761ms status=200 bytes=570
2017-01-02T15:56:46.236090+00:00 app[web.1]: 10.13.211.115 - - [02/Jan/2017 15:56:46] "POST /alexa HTTP/1.1" 200 -
2017-01-02T16:01:36.767042+00:00 heroku[router]: at=info method=POST path="/alexa" host=whispering-depths-44089.herokuapp.com request_id=e90e13cd-71ee-46be-98a6-dfa8524eb2f0 fwd="72.21.217.100" dyno=web.1 connect=1ms service=1248ms status=200 bytes=558
2017-01-02T16:01:36.761304+00:00 app[web.1]: 2017-01-02 16:01:36,760 - gmusicapi.Mobileclient3 (shared:281) [ERROR]: the response format for GetArtist was not recognized.
2017-01-02T16:01:36.761312+00:00 app[web.1]: 
2017-01-02T16:01:36.761313+00:00 app[web.1]: Value u'' for field '<obj>.albums[36].name' cannot be blank'
2017-01-02T16:01:36.761314+00:00 app[web.1]: 
2017-01-02T16:01:36.761316+00:00 app[web.1]: First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
2017-01-02T16:01:36.761317+00:00 app[web.1]: {u'method': u'GET', u'url': u'https://mclients.googleapis.com/sj/v2.5/fetchartist', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'nid': u'Ae3hkk6q7nm6zchy7ru4u5sxdle', u'dv': 0, u'hl': u'en_US', u'tier': u'aa', u'num-top-tracks': 5, u'include-albums': True, u'alt': u'json', u'num-related-artists': 5}}
2017-01-02T16:01:36.761318+00:00 app[web.1]: 
2017-01-02T16:01:36.761338+00:00 app[web.1]: with the Passengers project, and U2 promised their next album, to be released in the fall of...'
2017-01-02T16:01:36.761339+00:00 app[web.1]: A traceback follows:
2017-01-02T16:01:36.761340+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 249, in perform
2017-01-02T16:01:36.761340+00:00 app[web.1]:     cls.validate(response, parsed_response)
2017-01-02T16:01:36.761338+00:00 app[web.1]: u'{"kind":"sj#artist","name":"U2","artistArtRef":"http://lh3.googleusercontent.com/M0RlqsUx4hULw61OlxljLLxi0wlA__RSMZzF8Qgo7VCAWLOKkJMS6jiP9a3Gy4kwR63vh2Te4w","artistArtRefs":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/M0RlqsUx4hULw61OlxljLLxi0wlA__RSMZzF8Qgo7VCAWLOKkJMS6jiP9a3Gy4kwR63vh2Te4w","aspectRatio":"2","autogen":false}],"artistId":"Ae3hkk6q7nm6zchy7ru4u5sxdle","artistBio":"Through a combination of zealous righteousness and post-punk experimentalism, U2 became one of the most popular rock & roll bands of the \'80s. They were rock & roll crusaders during an era of synthesized pop and heavy metal, equally known for their sweeping sound as for their grandiose statements about politics and religion. The Edge provided the group with a signature sound by creating sweeping sonic landscapes with his heavily processed, echoed guitars. Though the Edge\'s style wasn\'t conventional, the rhythm section of Larry Mullen, Jr. and Adam Clayton played the songs as driving hard rock, giving the band a forceful, powerful edge that was designed for arenas. And their lead singer, Bono, was a frontman with a knack of grand gestures that played better in stadiums than small clubs. It\'s no accident that footage of Bono parading with a white flag with \\"Sunday Bloody Sunday\\" blaring in the background became the defining moment of U2\'s early career -- there rarely was a band that believed so deeply in rock\'s potential for revolution as U2, and there rarely was a band whose members didn\'t care if they appeared foolish in the process.\\n\\nDuring the course of the early \'80s, the group quickly built up a dedicated following through constant touring and a string of acclaimed records. By 1987, U2\'s following had grown large enough to propel them to the level of international superstardom with the release of The Joshua Tree. Unlike many of their contemporaries, they were able to sustain such popularity in the \'90s by reinventing themselves as a postmodern, self-consciously ironic, dance-inflected pop/rock act, owing equally to the experimentalism of late-\'70s Bowie and \'90s electronic dance and techno. By performing such a successful reinvention, the band confirmed its status as one of the most popular bands in rock history, in addition to earning additional critical respect.\\n\\nWith its textured guitars, the band\'s sound was undeniably indebted to post-punk, so it\'s slightly ironic that U2 formed in 1976, before punk had even reached their hometown of Dublin, Ireland. Larry Mullen Jr. (born October 31, 1961; drums), posted a notice on a high-school bulletin board asking for fellow musicians to form a band. Bono (born Paul Hewson, May 10, 1960; vocals), the Edge (born David Evans, August 8, 1961; guitar, keyboards, vocals), Adam Clayton (born March 13, 1960; bass), and Dick Evans responded to the ad, and the teenagers banded together as a Beatles and Stones cover band called the Feedback. They then changed their name to the Hype in 1977. Shortly afterward, Dick Evans left the band to form the Virgin Prunes, and the group changed names once again, this time adopting the moniker of U2.\\n\\nU2\'s first big break arrived in 1978, during the members\' final year of high school, when they won a talent contest sponsored by Guinness. By the end of the year, the Stranglers\' manager, Paul McGuinness, had seen U2 play and offered to manage them. Even with a powerful manager in their corner, the band had trouble making much headway, and failed an audition with CBS Records at the end of the year. In the fall of 1979, U2 released their debut EP, U2 Three. The EP was available only in Ireland, where it topped the national charts. Shortly afterward, they began to play in England, but they failed to gain much attention away from home.\\n\\nU2 scored one more chart-topping single, \\"Another Day,\\" in early 1980 before Island Records offered the group a contract. Later that year, the band\'s full-length debut, Boy, was released. Produced by Steve Lillywhite, the album\'s sweeping, atmospheric but edgy sound was unlike most recordings by U2\'s post-punk contemporaries, and the band earned further attention for its public embrace of Christianity; only Clayton was not a practicing Christian. Through constant touring, including opening gigs for Talking Heads, U2 were able to take Boy into the American Top 70 in early 1981. October, also produced by Lillywhite, followed in the fall, and it became their British breakthrough, reaching number 11 on the charts. By early 1983, Boy\'s \\"I Will Follow\\" and October\'s \\"Gloria\\" had become staples on MTV, which, along with their touring, gave U2 a formidable cult following in the U.S. \\n\\nReleased in the spring of 1983, the Lillywhite-produced War became U2\'s breakthrough release, entering the U.K. charts at number one and elevating them into arenas in the United States, where the album peaked at number 12. War had a stronger political message than its predecessors, as evidenced by the international hits \\"Sunday Bloody Sunday\\" and \\"New Year\'s Day.\\" During the supporting tour, the band filmed its concert at Colorado\'s Red Rocks Amphitheater, releasing the show as an EP and video titled Under a Blood Red Sky. The EP entered in the U.K. charts at number two, becoming the most successful live recording in British history. U2 had become one of the most popular bands in the world, and their righteous political stance soon became replicated by many other bands, providing the impetus for the Band Aid and Live Aid projects in 1984 and 1985, respectively. \\n\\nFor the follow-up to War, U2 entered the studios with co-producers Brian Eno and Daniel Lanois, who helped give the resulting album an experimental, atmospheric tone. Released in the fall of 1984, The Unforgettable Fire replicated the chart status of War, entering the U.K. charts at number one and reaching number 12 in the U.S. The album also generated the group\'s first Top 40 hit in America with \\"(Pride) In the Name of Love,\\" a tribute to Martin Luther King Jr. U2 supported the album with a successful international tour, highlighted by a show-stealing performance at Live Aid. Following the tour, the band released the live EP Wide Awake in America in 1985.\\n\\nWhile U2 had become one of the most successful rock bands of the \'80s, they didn\'t truly become superstars until the spring 1987 release of The Joshua Tree. Greeted with enthusiastic reviews, many of which proclaimed the album a masterpiece, The Joshua Tree became U2\'s first American number one hit and their third straight album to enter the U.K. charts at number one; in England, it set a record by going platinum within 28 hours. Generating the U.S. number one hits \\"With or Without You\\" and \\"I Still Haven\'t Found What I\'m Looking For,\\" The Joshua Tree and the group\'s supporting tour became the biggest success story of 1987, earning U2 the cover of respected publications like Time magazine. U2 decided to film a documentary about their American tour, recording new material along the way. The project became \\"Rattle & Hum\\", a film that was supported by a double-album soundtrack that was divided between live tracks and new material. While the album Rattle & Hum was a hit, the record and film received the weakest reviews of U2\'s career, with many critics taking issue with the group\'s fascination with American roots music like blues, soul, country, and folk. Following the release of Rattle & Hum, the band took an extended hiatus.\\n\\nU2 reconvened in Berlin in 1990 to record a new album with Eno and Lanois. While the sessions for the album were difficult, the resulting record, Achtung Baby, represented a successful reinvention of the band\'s trademark sound. Where they had been inspired by post-punk in the early career and American music during their mid-career, U2 delved into electronic and dance music with Achtung Baby. Inspired equally by late-\'70s Bowie and the Madchester scene in the U.K., Achtung Baby was sonically more eclectic and adventurous than U2\'s earlier work, and it didn\'t alienate their core audience. The album debuted at number one throughout the world and spawned Top Ten hits with \\"Mysterious Ways\\" and \\"One.\\" \\n\\nEarly in 1992, the group launched an elaborate tour to support Achtung Baby. Dubbed Zoo TV, the tour was an innovative blend of multimedia electronics, featuring a stage filled with televisions, suspended cars, and cellular phones. Bono devised an alter ego called the Fly, which was a knowing send-up of rock stardom. Even under the ironic guise of the Fly and Zoo TV, it was evident that U2 were looser and more fun than ever before, even though they had not abandoned their trademark righteous political anger. Following the completion of the American Zoo TV tour in late 1992 and preceding the launch of the tour\'s European leg, U2 entered the studio to complete an EP of new material that soon became the full-length Zooropa. Released in the summer of 1993 to coincide with the tour of the same name, Zooropa demonstrated a heavier techno and dance influence than Achtung Baby and received strong reviews. Nevertheless, the album stalled at sales of two million and failed to generate a big hit single. During the subsequent Zooropa tour, the Fly metamorphosed into the demonic MacPhisto, which dominated the remainder of the tour. Upon the completion of the Zooropa tour in late 1993, the band took another extended break.\\n\\nDuring 1995, U2 re-emerged with \\"Hold Me, Thrill Me, Kiss Me, Kill Me,\\" a glam rock theme to \\"Batman Forever\\" that was produced by Nellee Hooper (Bj\xf6rk, Soul II Soul). Later that year, they recorded the collaborative album Original Soundtracks, Vol. 1 with Brian Eno, releasing the record under the name the Passengers late in 1995. It was greeted with a muted reception, both critically and commercially. Many hardcore U2 fans (including drummer Larry Mullen Jr.) were unhappy 
2017-01-02T16:01:36.761338+00:00 app[web.1]: 
2017-01-02T16:01:36.761339+00:00 app[web.1]: Traceback (most recent call last):
2017-01-02T16:01:36.761341+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 627, in validate
2017-01-02T16:01:36.761341+00:00 app[web.1]:     raise_from(ValidationException(str(e)), e)
2017-01-02T16:01:36.761342+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/six.py", line 718, in raise_from
2017-01-02T16:01:36.761343+00:00 app[web.1]:     raise value
2017-01-02T16:01:36.761343+00:00 app[web.1]: ValidationException: Value u'' for field '<obj>.albums[36].name' cannot be blank'
2017-01-02T16:01:36.762915+00:00 app[web.1]: 10.158.160.96 - - [02/Jan/2017 16:01:36] "POST /alexa HTTP/1.1" 200 -
2017-01-02T16:01:37.735368+00:00 heroku[router]: at=info method=GET path="//stream/T6rrxaihpq3isrg6u6t53losasq" host=whispering-depths-44089.herokuapp.com request_id=087c6e72-5933-4b37-a589-bc092be619d1 fwd="96.35.47.222" dyno=web.1 connect=0ms service=2ms status=404 bytes=382
2017-01-02T16:01:37.735432+00:00 app[web.1]: 10.142.142.206 - - [02/Jan/2017 16:01:37] "GET //stream/T6rrxaihpq3isrg6u6t53losasq HTTP/1.1" 404 -
2017-01-02T16:01:37.944536+00:00 app[web.1]: 10.138.143.17 - - [02/Jan/2017 16:01:37] "POST /alexa HTTP/1.1" 400 -
2017-01-02T16:01:37.944654+00:00 heroku[router]: at=info method=POST path="/alexa" host=whispering-depths-44089.herokuapp.com request_id=03c55381-1a5b-4c80-b963-f894f0c83465 fwd="72.21.217.100" dyno=web.1 connect=1ms service=23ms status=400 bytes=164
2017-01-02T16:03:46.223341+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-01-02T16:03:46.223359+00:00 app[web.1]: DEBUG in selection [/app/geemusic/intents/selection.py:52]:
2017-01-02T16:03:46.223361+00:00 app[web.1]: Fetching song with or without you by None
2017-01-02T16:03:46.223362+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-01-02T16:03:46.674164+00:00 heroku[router]: at=info method=POST path="/alexa" host=whispering-depths-44089.herokuapp.com request_id=c34b9d4f-6a63-49eb-a301-8a37bbac5e03 fwd="72.21.217.100" dyno=web.1 connect=1ms service=960ms status=200 bytes=570
2017-01-02T16:03:46.673558+00:00 app[web.1]: 10.145.25.250 - - [02/Jan/2017 16:03:46] "POST /alexa HTTP/1.1" 200 -
2017-01-02T16:03:47.746303+00:00 heroku[router]: at=info method=GET path="//stream/Tygztregatldezon7h75hxeq77i" host=whispering-depths-44089.herokuapp.com request_id=97c723e9-41c6-4f90-86a5-28d83d3d9a88 fwd="96.35.47.222" dyno=web.1 connect=0ms service=1ms status=404 bytes=382
2017-01-02T16:03:47.745715+00:00 app[web.1]: 10.109.176.159 - - [02/Jan/2017 16:03:47] "GET //stream/Tygztregatldezon7h75hxeq77i HTTP/1.1" 404 -
2017-01-02T16:03:48.126530+00:00 heroku[router]: at=info method=POST path="/alexa" host=whispering-depths-44089.herokuapp.com request_id=cda173dc-b752-48c9-b7da-402dca5a28b1 fwd="72.21.217.100" dyno=web.1 connect=1ms service=30ms status=400 bytes=164
2017-01-02T16:03:48.121887+00:00 app[web.1]: 10.154.74.169 - - [02/Jan/2017 16:03:48] "POST /alexa HTTP/1.1" 400 -
2017-01-02T16:09:49.707811+00:00 app[web.1]: 10.238.25.185 - - [02/Jan/2017 16:09:49] "GET / HTTP/1.1" 404 -
2017-01-02T16:09:49.708951+00:00 heroku[router]: at=info method=GET path="/" host=whispering-depths-44089.herokuapp.com request_id=5eda6374-a15f-42ab-8b4a-2cd5bee230af fwd="96.35.47.222" dyno=web.1 connect=0ms service=2ms status=404 bytes=382
2017-01-02T16:09:50.038385+00:00 app[web.1]: 10.238.25.185 - - [02/Jan/2017 16:09:50] "GET /favicon.ico HTTP/1.1" 404 -
2017-01-02T16:09:50.039626+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=whispering-depths-44089.herokuapp.com request_id=aeecdb7c-771c-45ab-bc3c-5a5aa1adc120 fwd="96.35.47.222" dyno=web.1 connect=1ms service=2ms status=404 bytes=382
2017-01-02T16:15:00.281483+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-01-02T16:15:00.281498+00:00 app[web.1]: DEBUG in selection [/app/geemusic/intents/selection.py:52]:
2017-01-02T16:15:00.281500+00:00 app[web.1]: Fetching song with or without you by None
2017-01-02T16:15:00.281501+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-01-02T16:15:00.729836+00:00 heroku[router]: at=info method=POST path="/alexa" host=whispering-depths-44089.herokuapp.com request_id=db11922a-1172-4d53-913b-b37287387453 fwd="72.21.217.162" dyno=web.1 connect=1ms service=1158ms status=200 bytes=570
2017-01-02T16:15:00.731896+00:00 app[web.1]: 10.171.127.156 - - [02/Jan/2017 16:15:00] "POST /alexa HTTP/1.1" 200 -

**Comment by stevenleeg** [comment]
Hey, this sounds to me like you have the `APP_URL` variable set incorrectly in your Heroku app's configuration. Could you double check that it's set to something like `https://some-app.herokuapp.com` (*without* a trailing slash)?

**Comment by jeffko77** [comment]
That was it!  Thanks so much. Now I see a bunch of URL's being sent. I am good to go! Thanks so much.
