### ISSUE TITLE
Listing album fails with TypeError

### ISSUE THREAD

**Issue by yunyu** [stevenleeg/geemusic#115]
Whenever I list ask geemusic to list albums for any artist, I get:

```
16:44:08 web.1  | 127.0.0.1 - - [22/Jul/2017 16:44:08] "POST /alexa HTTP/1.1" 500 -
16:44:08 web.1  | Traceback (most recent call last):
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
16:44:08 web.1  |     return self.wsgi_app(environ, start_response)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
16:44:08 web.1  |     response = self.handle_exception(e)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
16:44:08 web.1  |     reraise(exc_type, exc_value, tb)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
16:44:08 web.1  |     raise value
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
16:44:08 web.1  |     response = self.full_dispatch_request()
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
16:44:08 web.1  |     rv = self.handle_user_exception(e)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
16:44:08 web.1  |     reraise(exc_type, exc_value, tb)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
16:44:08 web.1  |     raise value
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
16:44:08 web.1  |     rv = self.dispatch_request()
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
16:44:08 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask_ask/core.py", line 560, in _flask_view_func
16:44:08 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
16:44:08 web.1  |   File "/home/appserver/geemusic/geemusic/intents/selection.py", line 231, in list_album_by_artists
16:44:08 web.1  |     return statement(artist_album_list)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask_ask/models.py", line 106, in __init__
16:44:08 web.1  |     super(statement, self).__init__(speech)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask_ask/models.py", line 53, in __init__
16:44:08 web.1  |     'outputSpeech': _output_speech(speech)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/envs/geemusic/lib/python3.6/site-packages/flask_ask/models.py", line 245, in _output_speech
16:44:08 web.1  |     xmldoc = ElementTree.fromstring(speech)
16:44:08 web.1  |   File "/home/appserver/.pyenv/versions/3.6.2/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
16:44:08 web.1  |     parser.feed(text)
16:44:08 web.1  | TypeError: a bytes-like object is required, not 'bool'
```

**Comment by Danondso** [comment]
What artist was it? I can't look at this atm since I'm on vacation but I
can investigate when I get back.

**Comment by yunyu** [comment]
I tried with Robert Miles, Aphex Twin, and John Murphy. The obvious issue is that get_latest_artist_albums returns False if the list is empty (which should be fixed to return a string), but geemusic plays songs and albums by those artists correctly (e.g. asking geemusic to "play album dreamland") outputs "playing Dreamland by Robert Miles) which means that the list shouldn't be empty.

**Comment by Danondso** [comment]
Quick update here:
I replaced that False with a string, so you get an error message now instead of a stacktrace.
Also fixed the debug entry, you can use the intent without specifying an artist, so whenever it was logging a request based only on album name there was nothing to log for artist.
