### ISSUE TITLE
Can't run app due to KeyError: 'DEBUG_MODE'

### ISSUE THREAD

**Issue by loctruong96** [stevenleeg/geemusic#120]
```
2017-08-09T09:19:27.979947+00:00 app[web.1]: Traceback (most recent call last):
2017-08-09T09:19:27.979965+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-08-09T09:19:27.980123+00:00 app[web.1]:     from geemusic import app
2017-08-09T09:19:27.980139+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 13, in <module>
2017-08-09T09:19:27.980217+00:00 app[web.1]:     if str(environ['DEBUG_MODE']) is True:
2017-08-09T09:19:27.980218+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2017-08-09T09:19:27.980663+00:00 app[web.1]:     raise KeyError(key) from None
2017-08-09T09:19:27.980693+00:00 app[web.1]: KeyError: 'DEBUG_MODE'
2017-08-09T09:19:28.154756+00:00 heroku[web.1]: State changed from starting to crashed
2017-08-09T09:19:28.142156+00:00 heroku[web.1]: Process exited with status 1
```
I am having this problem both on heroku and local, please help! Thank you so much in advance!

**Comment by newone757** [comment]
I just had this problem and got some awesome help here. See issue 118

https://github.com/stevenleeg/geemusic/issues/118

**Comment by loctruong96** [comment]
Thank you, I solved this problem.
