### ISSUE TITLE
Special Logging Instruction?

### ISSUE THREAD

**Issue by loctruong96** [stevenleeg/geemusic#121]
Hello I got through the debugger issue by turning it off. But now to the actual login, I can't login. I was pretty sure i am using the correct password. What confused me was that google didn't even recognize the login attempt from my app on heroku.  Is there a special step for logging?  Here is the log:
`2017-08-09T17:43:44.224483+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2017-08-09T17:43:49.676759+00:00 heroku[web.1]: Process exited with status 1
2017-08-09T17:43:49.480858+00:00 app[web.1]: Traceback (most recent call last):
2017-08-09T17:43:49.480875+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-08-09T17:43:49.481007+00:00 app[web.1]:     from geemusic import app
2017-08-09T17:43:49.481008+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 20, in <module>
2017-08-09T17:43:49.481151+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)
2017-08-09T17:43:49.481154+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 265, in generate_api
2017-08-09T17:43:49.481316+00:00 app[web.1]:     **kwargs)
2017-08-09T17:43:49.481318+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 17, in __init__
2017-08-09T17:43:49.481419+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")
2017-08-09T17:43:49.481420+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!
2017-08-09T17:43:49.690780+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by loctruong96** [comment]
oh. Never mind. I tried to setup app password and it works.
