### ISSUE TITLE
Getting a KeyError whether using Foreman or heroku 

### ISSUE THREAD

**Issue by tablifiedapps** [stevenleeg/geemusic#125]
`2017-08-28T05:19:09.684174+00:00 app[web.1]: Traceback (most recent call last):
2017-08-28T05:19:09.684187+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-08-28T05:19:09.684390+00:00 app[web.1]:     from geemusic import app
2017-08-28T05:19:09.684412+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 13, in <module>
2017-08-28T05:19:09.684562+00:00 app[web.1]:     if str(environ['DEBUG_MODE']) is True:
2017-08-28T05:19:09.684584+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2017-08-28T05:19:09.685086+00:00 app[web.1]:     raise KeyError(key) from None
2017-08-28T05:19:09.685114+00:00 app[web.1]: KeyError: 'DEBUG_MODE'`

I am getting the same error with Foreman so I moved everything but moved to heroku and getting the same error in the logs. Could someone point me in the right direction?

**Comment by computerfreaq09** [comment]
I would like to confirm this, as I am also getting KeyErrors

**Comment by jmahlman** [comment]
I too get this error.

**Comment by huberf** [comment]
Have you added `export DEBUG_MODE=True` to your environment variables? If not, this should resolve the initial issue as my install works perfectly. If on Heroku, go to Settings>Config Variables and set the appropriate things up there. If you haven't set up the login info as well, you will certainly need to do this. If you have any questions about how to do any of this, let me know and I'll post something more detailed.

**Comment by jmahlman** [comment]
Yup, that helped without commenting the lines out.  Just run:
`heroku config:set DEBUG_MODE=TRUE`

**Comment by huberf** [comment]
For anyone experience the issue, one need only run `heroku config:set DEBUG_MODE=True` as @jmahlman stated. I've submitted a PR which updates the documentation with this step: https://github.com/stevenleeg/geemusic/pull/131

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
