### ISSUE TITLE
Crashes in Heroku

### ISSUE THREAD

**Issue by Mutate** [stevenleeg/geemusic#142]
I have tried building this in Heroku repeatedly with the same result every time.  I would appreciate it if someone could help.  When I test in the Amazon Alexa service simulator, I get "There was an error calling the remote endpoint, which returned HTTP 503 : Service Unavailable".

`2017-10-09T05:25:04.298341+00:00 heroku[web.1]: State changed from crashed to starting
2017-10-09T05:25:10.405689+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2017-10-09T05:25:16.277923+00:00 app[web.1]: Traceback (most recent call last):
2017-10-09T05:25:16.280477+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-10-09T05:25:16.280722+00:00 app[web.1]:     from geemusic import app
2017-10-09T05:25:16.280759+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 20, in <module>
2017-10-09T05:25:16.280893+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)
2017-10-09T05:25:16.280961+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 264, in generate_api
2017-10-09T05:25:16.281232+00:00 app[web.1]:     **kwargs)
2017-10-09T05:25:16.281256+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 17, in __init__
2017-10-09T05:25:16.281436+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")
2017-10-09T05:25:16.281466+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!
2017-10-09T05:25:16.688288+00:00 heroku[web.1]: Process exited with status 1
2017-10-09T05:25:16.703137+00:00 heroku[web.1]: State changed from starting to crashed
2017-10-09T05:25:16.706118+00:00 heroku[web.1]: State changed from crashed to starting
2017-10-09T05:25:22.728281+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2017-10-09T05:25:28.135366+00:00 heroku[web.1]: Process exited with status 1
2017-10-09T05:25:27.939119+00:00 app[web.1]: Traceback (most recent call last):
2017-10-09T05:25:27.939133+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-10-09T05:25:27.939314+00:00 app[web.1]:     from geemusic import app
2017-10-09T05:25:27.939332+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 20, in <module>
2017-10-09T05:25:27.939476+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)
2017-10-09T05:25:27.939493+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 264, in generate_api
2017-10-09T05:25:27.939759+00:00 app[web.1]:     **kwargs)
2017-10-09T05:25:27.939777+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 17, in __init__
2017-10-09T05:25:27.939926+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")
2017-10-09T05:25:27.939953+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!
2017-10-09T05:25:28.152927+00:00 heroku[web.1]: State changed from starting to crashed
2017-10-09T05:27:31.737464+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=gentle-dawn-34573.herokuapp.com request_id=97f93d66-d2bd-4e64-9ee7-d4c5c54c5f1f fwd="72.21.217.152" dyno= connect= service= status=503 bytes= protocol=https`

Any assistance would be greatly appreciated.

**Comment by SquareTheBase** [comment]
It looks like your Google credentials are incorrect.  Have you created an app password?

**Comment by Mutate** [comment]
@SquareTheBase 
You are the man.  This tip should be included in the heroku app setup.  That fixed the issue right away.  Thanks a bunch.  Issue closed.
