### ISSUE TITLE
Alexa cannot find anything

### ISSUE THREAD

**Issue by matthewodf** [stevenleeg/geemusic#157]
This just stopped working. I have now enabled 2 factor Authentication and  created an app password. This has been changed in the .env. The skill tests fine with "help" and I see a response on the foreman and ngrok screens but Alexa cannot find anything when I ask for songs, albums, artists, etc. and no response is logged in foreman or ngrok. As I said, this was working perfectly for ages.

**Comment by alexargo** [comment]
I'm getting a similar issue. Here's the log output:

```
2017-11-28T01:38:44.304326+00:00 heroku[router]: at=info method=GET path="/alexa/stream/Trp6xwxhgsuxs7sv5ugy45wm7au" host=geemusic-argo.herokuapp.com request_id=c1bc4158-83f4-4c4e-a63f-77c2b3383019 fwd="72.49.196.215" dyno=web.1 connect=1ms service=222ms status=500 bytes=33296 protocol=https
2017-11-28T01:38:44.301404+00:00 app[web.1]: 10.41.160.188 - - [28/Nov/2017 01:38:44] "GET /alexa/stream/Trp6xwxhgsuxs7sv5ugy45wm7au HTTP/1.1" 500 -
2017-11-28T01:38:44.301796+00:00 app[web.1]: Traceback (most recent call last):
2017-11-28T01:38:44.301798+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
2017-11-28T01:38:44.301799+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2017-11-28T01:38:44.301800+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
2017-11-28T01:38:44.301801+00:00 app[web.1]:     response = self.handle_exception(e)
2017-11-28T01:38:44.301802+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
2017-11-28T01:38:44.301802+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-11-28T01:38:44.301803+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-11-28T01:38:44.301804+00:00 app[web.1]:     raise value
2017-11-28T01:38:44.301804+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-11-28T01:38:44.301805+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-11-28T01:38:44.301806+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-11-28T01:38:44.301806+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-11-28T01:38:44.301810+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-11-28T01:38:44.301811+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-11-28T01:38:44.301811+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-11-28T01:38:44.301812+00:00 app[web.1]:     raise value
2017-11-28T01:38:44.301812+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-11-28T01:38:44.301813+00:00 app[web.1]:     rv = self.dispatch_request()
2017-11-28T01:38:44.301814+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-11-28T01:38:44.301814+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-11-28T01:38:44.301816+00:00 app[web.1]:   File "/app/geemusic/controllers.py", line 9, in redirect_to_stream
2017-11-28T01:38:44.301816+00:00 app[web.1]:     stream_url = api.get_google_stream_url(song_id)
2017-11-28T01:38:44.301817+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 145, in get_google_stream_url
2017-11-28T01:38:44.301818+00:00 app[web.1]:     return self._api.get_stream_url(song_id)
2017-11-28T01:38:44.301818+00:00 app[web.1]:   File "<decorator-gen-102>", line 2, in get_stream_url
2017-11-28T01:38:44.301819+00:00 app[web.1]:     
2017-11-28T01:38:44.301819+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
2017-11-28T01:38:44.301820+00:00 app[web.1]:     return function(*args, **kw)
2017-11-28T01:38:44.301821+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gmusicapi/clients/mobileclient.py", line 388, in get_stream_url
2017-11-28T01:38:44.301822+00:00 app[web.1]:     return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
2017-11-28T01:38:44.301822+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
2017-11-28T01:38:44.301823+00:00 app[web.1]:     return protocol.perform(self.session, self.validate, *args, **kwargs)
2017-11-28T01:38:44.301824+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
2017-11-28T01:38:44.301825+00:00 app[web.1]:     raise CallFailure(err_msg, call_name)
2017-11-28T01:38:44.301826+00:00 app[web.1]: gmusicapi.exceptions.CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=hi&net=mob&pt=e&slt=1511833124117&sig=1rsupUmK2zlNGS132t5ecnrx7lU&mjck=Trp6xwxhgsuxs7sv5ugy45wm7au&hl=en_US&dv=0&tier=aa
2017-11-28T01:38:44.301827+00:00 app[web.1]: (requests kwargs: {'method': 'GET', 'url': 'https://mclients.googleapis.com/music/mplay', 'allow_redirects': False, 'headers': {'X-Device-ID': 'BA94E0E3C0F1', 'Authorization': '<omitted>'}, 'params': {'opt': 'hi', 'net': 'mob', 'pt': 'e', 'slt': '1511833124117', 'sig': b'1rsupUmK2zlNGS132t5ecnrx7lU', 'mjck': 'Trp6xwxhgsuxs7sv5ugy45wm7au', 'hl': 'en_US', 'dv': 0, 'tier': 'aa'}})
2017-11-28T01:38:44.301828+00:00 app[web.1]: (response was: '<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
```

**Comment by fergyfresh** [comment]
You may have invalidated your app password in google. Seems like a Google App Password issue since you're getting invalid auth, which is on Google's end and seemingly not in geemusic's end. My $0.02 FWIW.

**Comment by alexargo** [comment]
Turns out my specific issue was I had used up all 10 of my devices. No way to tell that was it. I eventually was adding a different phone and got the error message so I went and deleted a bunch of old devices and everything is working now. This may not be matthewodf's issue, though.

I wonder if mentioning the devices in the readme would be helpful. I doubt it's possible to give an error message from gee music itself.

**Comment by fergyfresh** [comment]
I don't think they would want to be in the business of hosting up to date requirements of Google's internal account management stuff. That's just my $0.02

**Comment by matthewodf** [comment]
Thanks for the feedback. I will continue to try different things and see
where I get to.
