### ISSUE TITLE
`/alexa` or not and other errors

### ISSUE THREAD

**Issue by alex-phillips** [stevenleeg/geemusic#201]
I'm pretty confused with the docs. Half of them say to be sure to use `/alexa` at the end of the endpoint URLs, but docker deploy doesn't mention it at all. When using docker, do I need to include `/alexa` at the end of the environment variable? Or just the Amazon config endpoint? Or both?

Also, I don't know if what I have is working but no matter what intent I test, I get a `TemplateNotFound is not iterable`. See below:

Intent: Play songs by Pink Floyd
```
14:26:16 web.1  | Traceback (most recent call last):
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
14:26:16 web.1  |     return self.wsgi_app(environ, start_response)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
14:26:16 web.1  |     response = self.handle_exception(e)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
14:26:16 web.1  |     reraise(exc_type, exc_value, tb)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
14:26:16 web.1  |     raise value
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
14:26:16 web.1  |     response = self.full_dispatch_request()
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
14:26:16 web.1  |     rv = self.handle_user_exception(e)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
14:26:16 web.1  |     reraise(exc_type, exc_value, tb)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
14:26:16 web.1  |     raise value
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
14:26:16 web.1  |     rv = self.dispatch_request()
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
14:26:16 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask_ask/core.py", line 629, in _flask_view_func
14:26:16 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
14:26:16 web.1  |   File "/geemusic/geemusic/intents/selection.py", line 29, in play_artist
14:26:16 web.1  |     return statement(render_template("play_artist_none"))
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
14:26:16 web.1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
14:26:16 web.1  |     return self.get_template(template_name_or_list, parent, globals)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
14:26:16 web.1  |     return self._load_template(name, self.make_globals(globals))
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
14:26:16 web.1  |     template = self.loader.load(self, name, globals)
14:26:16 web.1  |   File "/usr/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
14:26:16 web.1  |     source, filename, uptodate = self.get_source(environment, name)
14:26:16 web.1  | TypeError: 'TemplateNotFound' object is not iterable
```

**Comment by fergyfresh** [comment]
It can't find the `template/en.yaml`. Whats ur __init__.py look like? You change it from the default for this repo?
