### ISSUE TITLE
Am I too stupid to deploy on AWS?

### ISSUE THREAD

**Issue by ctolkmit** [stevenleeg/geemusic#270]
Hi,

following the README I am trying to deploy the skill to AWS Lambda. 
I have my User with Admin Permissions, I did `aws configure`, I do have `zappa_settings.json` but when I do `zappa deploy dev` the following error occurrs:

```
(.venv) ctolkmit@inferno:~/OtherWorkspace/geemusic$ zappa deploy dev
/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
(python-dateutil 2.7.5 (/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages), Requirement.parse('python-dateutil==2.6.1'), {'zappa'})
Calling deploy for stage dev..
Downloading and installing dependencies..
 - protobuf==3.3.0: Using locally cached manylinux wheel
 - cryptography==2.3.1: Warning! Using precompiled lambda package version 1.9 instead!
 - cffi==1.10.0: Using locally cached manylinux wheel
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/zappa/core.py", line 884, in upload_to_s3
    self.s3_client.head_bucket(Bucket=bucket_name)
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/zappa/cli.py", line 714, in deploy
    self.zip_path, self.s3_bucket_name, disable_progress=self.disable_progress)
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/zappa/core.py", line 896, in upload_to_s3
    CreateBucketConfiguration={'LocationConstraint': self.aws_region},
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ctolkmit/OtherWorkspace/geemusic/.venv/lib/python3.6/site-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BucketAlreadyExists: An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
```

Right now I do not know where I could look or adjust anything to find out what went wrong. Anybody here can give me a pointer?

**Comment by ctolkmit** [comment]
When I created the s3_bucket from the zappa_config.json beforehand, it worked.

**Comment by fergyfresh** [comment]
Glad you figured it out. I'm just stopping by to say, you're not stupid.
