### ISSUE TITLE
Heroku instance error

### ISSUE THREAD

**Issue by egi78** [stevenleeg/geemusic#271]
Hi Steven,
I’m from Italy. I’m trying to setup a Heroku instance but after having filled in the relevant data in heroku site, when I click on “deploy app” I have the following
https://imageshack.com/i/pldGHT7Yp
What can you suggest me to solve?
Thanks

**Comment by tcpaulh** [comment]
Same problem here

**Comment by fergyfresh** [comment]
Maybe try the whole setup from scratch again. I have never heard of that issue. Maybe you have royally messed something up. Sometimes starting over from scratch will help turn on a lightbulb that was previously very cloudy.

**Comment by tcpaulh** [comment]
Thanks but no dice the 4 or 5 times I've tried. Will be able to try again later

**Comment by tcpaulh** [comment]
OK, it's working today. A glitch in the matrix. Now I've deployed to Heroku I'm looking for speech_assets/non_us_custom_slot_version/interactionModel.json so I can paste the contents into the json editor in the interaction model.... 

Where do I look for the file? It's not clear (to me :eek:) from the instructions

**Comment by tcpaulh** [comment]
<img width="706" alt="unexpected at row 6" src="https://user-images.githubusercontent.com/2441192/49395834-7ac42a80-f72f-11e8-8f0e-bf53ae988522.png">

**Comment by tcpaulh** [comment]
Great, now google insists there's been suspicious activity on my account and that I must change my password. There doesn't seem to be a way round it and it wont let me use the old one. :-O

**Comment by fergyfresh** [comment]
Yeah. You gotta use the 2FA especially with the PAAS setup (Heroku, AWS, Digital Ocean, etc) Glad you're not having trouble with anthing else though. So you just want the contents of the `view raw` section of that file (just the json, none of the html if you were to do something like `right click -> view source`.

**Comment by tcpaulh** [comment]
Thanks :) I've enabled 2FA and changed the password var in heroku. Will it automatically retry the login with the new credentials? Or do I have to force it?

**Comment by tcpaulh** [comment]
On the developer console test tab I enter "Ask gee music to play some music" and get "There was a problem with the requested skill's response"

**Comment by fergyfresh** [comment]
Yeah. I think you'll have to restart the app. https://github.com/stevenleeg/geemusic/blob/master/geemusic/__init__.py#L30 logs in on app startup.

**Comment by tcpaulh** [comment]
Thanks again and sorry for the newbie stuff. It's a learning curve but I seem to be getting there. I've selected "restart all dynos" in the 'more' menu in heroku web interface. Presumably I should get a 2FA popup on my android phone shortly...?

**Comment by tcpaulh** [comment]
Heh, this is frustating :) I've had no 2FA popup after restarting dynos and when I 'ask gee music to play some music' on the test tab of the alexa developer console I get "There was a problem with the requested skill's response"

**Comment by fergyfresh** [comment]
There is no popup. This is ghetto jerry rig setup.

**Comment by tcpaulh** [comment]
Not expecting one from the app. Was expecting google to go through 2fa when login from heroku was attempted and give me a toast/notification on my android phone, or an email, or something. Basically I don't know if the app has logged in successfully. Getting 503 error when invoking  "play some music" from alexa developer console

**Comment by tcpaulh** [comment]
[code]2018-12-03T21:35:10.884122+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tcpgeemusic.herokuapp.com request_id=5ec44b7b-4bb7-4ecc-9a14-01c3ab8070eb fwd="23.20.207.92" dyno= connect= service= status=503 bytes= protocol=http
2018-12-03T21:50:08.897362+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=c25e1ae6-9b0f-4945-b37b-7396c2aff41b fwd="54.240.197.65" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:50:09.638977+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=bd9bdbff-9be4-4d0b-a367-eeaa1951c814 fwd="54.240.197.65" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:50:25.896931+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=0212983e-76f5-4340-a7fa-32eb8150ffbc fwd="54.240.197.65" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:50:26.360014+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=25d2c5a2-940a-4aa4-938c-8461bb807364 fwd="54.240.197.65" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:55:52.082964+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=95fcb88e-afce-4d8d-8b9b-1b0ff71ef510 fwd="54.240.197.65" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:55:52.566231+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=0e7f26e6-6ff7-4db1-910e-4bb52d8f9d71 fwd="54.240.197.65" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:56:35.457439+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=45739d5f-eab8-4c72-92de-07b41eb5b44f fwd="54.240.197.107" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T21:56:37.031448+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/alexa" host=tcpgeemusic.herokuapp.com request_id=acdb910d-8b67-4b7b-92ba-7a5e921c26e1 fwd="54.240.197.107" dyno= connect= service= status=503 bytes= protocol=https
2018-12-03T22:05:02.971044+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tcpgeemusic.herokuapp.com request_id=af35a796-1bf2-4eb5-ba23-835e855013d7 fwd="54.81.66.118" dyno= connect= service= status=503 bytes= protocol=http
2018-12-03T22:17:02.704189+00:00 heroku[web.1]: State changed from crashed to starting
2018-12-03T22:17:11.454114+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2018-12-03T22:17:15.876045+00:00 app[web.1]: Traceback (most recent call last):
2018-12-03T22:17:15.876073+00:00 app[web.1]:   File "server.py", line 1, in <module>
2018-12-03T22:17:15.876263+00:00 app[web.1]:     from geemusic import app
2018-12-03T22:17:15.876266+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 30, in <module>
2018-12-03T22:17:15.876446+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)
2018-12-03T22:17:15.876450+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 274, in generate_api
2018-12-03T22:17:15.876746+00:00 app[web.1]:     **kwargs)
2018-12-03T22:17:15.876753+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 17, in __init__
2018-12-03T22:17:15.876920+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")
2018-12-03T22:17:15.876967+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!
2018-12-03T22:17:16.457826+00:00 heroku[web.1]: State changed from starting to crashed
2018-12-03T22:17:16.426446+00:00 heroku[web.1]: Process exited with status 1
[/code]
