### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509V3_EXT_get'

### ISSUE THREAD

**Issue by dony71** [stevenleeg/geemusic#284]
doing test using alexa simulator, get response
"There was a problem with the requested skill's response"

debug error on the server shows :
21:20:35 web.1  | 127.0.0.1 - - [25/Mar/2019 21:20:35] "POST /alexa HTTP/1.1" 500 -
21:21:06 web.1  | Traceback (most recent call last):
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
21:21:06 web.1  |     return self.wsgi_app(environ, start_response)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
21:21:06 web.1  |     response = self.handle_exception(e)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
21:21:06 web.1  |     reraise(exc_type, exc_value, tb)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
21:21:06 web.1  |     raise value
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
21:21:06 web.1  |     response = self.full_dispatch_request()
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_requ                       est
21:21:06 web.1  |     rv = self.handle_user_exception(e)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_except                       ion
21:21:06 web.1  |     reraise(exc_type, exc_value, tb)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
21:21:06 web.1  |     raise value
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_requ                       est
21:21:06 web.1  |     rv = self.dispatch_request()
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
21:21:06 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask_ask/core.py", line 728, in _flask_view_fu                       nc
21:21:06 web.1  |     ask_payload = self._alexa_request(verify=self.ask_verify_requests)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask_ask/core.py", line 662, in _alexa_request
21:21:06 web.1  |     cert = verifier.load_certificate(cert_url)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask_ask/verifier.py", line 21, in load_certif                       icate
21:21:06 web.1  |     if not _valid_certificate(cert):
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask_ask/verifier.py", line 63, in _valid_cert                       ificate
21:21:06 web.1  |     value = str(extension)
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/OpenSSL/crypto.py", line 779, in __str__
21:21:06 web.1  |     return self._subjectAltNameString()
21:21:06 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/OpenSSL/crypto.py", line 740, in _subjectAltNam                       eString
21:21:06 web.1  |     method = _lib.X509V3_EXT_get(self._extension)
21:21:06 web.1  | AttributeError: module 'lib' has no attribute 'X509V3_EXT_get'

**Comment by dony71** [comment]
fix by pip install 'cryptography<2.2'
check this
https://stackoverflow.com/questions/49375054/alexa-skill-development-using-flask-ask-and-ngrok
