### ISSUE TITLE
"AttributeError: module 'lib' has no attribute 'X509V3_EXT_get' " error message when GeeMusic server receives a request

### ISSUE THREAD

**Issue by megamalain** [stevenleeg/geemusic#286]
09:39:49 web.1  | --------------------------------------------------------------------------------
09:40:54 web.1  | 127.0.0.1 - - [18/Apr/2019 09:40:54] "POST /alexa HTTP/1.1" 500 -
09:40:55 web.1  | Traceback (most recent call last):
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
09:40:55 web.1  |     return self.wsgi_app(environ, start_response)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
09:40:55 web.1  |     response = self.handle_exception(e)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
09:40:55 web.1  |     reraise(exc_type, exc_value, tb)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
09:40:55 web.1  |     raise value
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
09:40:55 web.1  |     response = self.full_dispatch_request()
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
09:40:55 web.1  |     rv = self.handle_user_exception(e)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
09:40:55 web.1  |     reraise(exc_type, exc_value, tb)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
09:40:55 web.1  |     raise value
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
09:40:55 web.1  |     rv = self.dispatch_request()
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
09:40:55 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 728, in _flask_view_func
09:40:55 web.1  |     ask_payload = self._alexa_request(verify=self.ask_verify_requests)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 662, in _alexa_request
09:40:55 web.1  |     cert = verifier.load_certificate(cert_url)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask_ask/verifier.py", line 21, in load_certificate
09:40:55 web.1  |     if not _valid_certificate(cert):
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/flask_ask/verifier.py", line 63, in _valid_certificate
09:40:55 web.1  |     value = str(extension)
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/OpenSSL/crypto.py", line 779, in __str__
09:40:55 web.1  |     return self._subjectAltNameString()
09:40:55 web.1  |   File "/home/pi/geemusic/.venv/lib/python3.5/site-packages/OpenSSL/crypto.py", line 740, in _subjectAltNameString
09:40:55 web.1  |     method = _lib.X509V3_EXT_get(self._extension)
09:40:55 web.1  | AttributeError: module 'lib' has no attribute 'X509V3_EXT_get'
09:40:55 web.1  | 127.0.0.1 - - [18/Apr/2019 09:40:55] "POST /alexa HTTP/1.1" 500 -

**Comment by megamalain** [comment]
pip3 install 'cryptography<2.2'
