### ISSUE TITLE
Docker Image Build Fails

### ISSUE THREAD

**Issue by mikepruett3** [stevenleeg/geemusic#302]
Trying to build the docker image using the included Dockerfile fails with the following error...

_Collecting lambda-packages==0.19.0 (from -r /tmp/requirements.txt (line 34))
  Downloading https://files.pythonhosted.org/packages/e5/52/fb693a38c1cac26e03f67cd16e9eb32dbe3852d444885d0c869be33ad9e1/lambda_packages-0.19.0.tar.gz (74.1MB)
The command '/bin/sh -c pip wheel --wheel-dir=/root/wheels -r /tmp/requirements.txt' returned a non-zero code: 137_

I'm sure it has something to do with the version of the lambda-packages... but I don't have much to go on.

Any help would be appreciated!

Docker Version: 

```bash
# docker --version
Docker version 19.03.4, build 9013bf583a
```

Server Version:

```bash
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

Full Output:

```bash
# docker build -t geemusic .
free(): invalid pointer
SIGABRT: abort
PC=0x7f63214f6e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42004fcc0, 0xc42004fce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004fc90 sp=0xc42004fc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xc2b270)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42004fcc0 sp=0xc42004fc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xc2b270)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42004fcf8 sp=0xc42004fcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420016340)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42004fda0 sp=0xc42004fcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42004fe88, 0x410022, 0xc4200162a0)
        <autogenerated>:4 +0x46 fp=0xc42004fde0 sp=0xc42004fda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)             /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42004fe68 sp=0xc42004fde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffe852066ff, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42004fed8 sp=0xc42004fe68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42004ff58 sp=0xc42004fed8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42004ff88 sp=0xc42004ff58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42004ffe0 sp=0xc42004ff88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffe85204b80
rcx    0x7f63214f6e97
rdx    0x0
rdi    0x2
rsi    0x7ffe85204910
rbp    0x7ffe85204c80
rsp    0x7ffe85204910
r8     0x0
r9     0x7ffe85204910
r10    0x8
r11    0x246
r12    0x7ffe85204b80
r13    0x1000
r14    0x0
r15    0x30
rip    0x7f63214f6e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon  268.8kB
Step 1/13 : FROM python:3.7-alpine as python-base
 ---> 13f1d829523b
Step 2/13 : MAINTAINER Spencer Julian <hellothere@spencerjulian.com>
 ---> Running in 58a6e096cdc5
Removing intermediate container 58a6e096cdc5
 ---> 3ed68be7a0a1
Step 3/13 : RUN apk add --no-cache --update curl wget build-base libffi-dev openssl-dev
 ---> Running in 15200d44bdb2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/26) Installing libgcc (9.2.0-r3)
(2/26) Installing libstdc++ (9.2.0-r3)
(3/26) Installing binutils (2.33.1-r0)
(4/26) Installing libmagic (5.37-r1)
(5/26) Installing file (5.37-r1)
(6/26) Installing gmp (6.1.2-r1)
(7/26) Installing isl (0.18-r0)
(8/26) Installing libgomp (9.2.0-r3)
(9/26) Installing libatomic (9.2.0-r3)
(10/26) Installing mpfr4 (4.0.2-r1)
(11/26) Installing mpc1 (1.1.0-r1)
(12/26) Installing gcc (9.2.0-r3)
(13/26) Installing musl-dev (1.1.24-r1)
(14/26) Installing libc-dev (0.7.2-r0)
(15/26) Installing g++ (9.2.0-r3)
(16/26) Installing make (4.2.1-r2)
(17/26) Installing fortify-headers (1.1-r0)
(18/26) Installing build-base (0.5-r1)
(19/26) Installing nghttp2-libs (1.40.0-r0)
(20/26) Installing libcurl (7.67.0-r0)
(21/26) Installing curl (7.67.0-r0)
(22/26) Installing linux-headers (4.19.36-r0)
(23/26) Installing pkgconf (1.6.3-r0)
(24/26) Installing libffi-dev (3.2.1-r6)
(25/26) Installing openssl-dev (1.1.1d-r3)
(26/26) Installing wget (1.20.3-r0)
Executing busybox-1.31.1-r9.trigger
OK: 192 MiB in 60 packages
Removing intermediate container 15200d44bdb2
 ---> 327691ab1589
Step 4/13 : COPY requirements.txt /tmp
 ---> f6fda9123614
Step 5/13 : RUN pip install -U 'pip<10'
 ---> Running in 56e2de370d2a
Collecting pip<10
  Downloading pip-9.0.3-py2.py3-none-any.whl (1.4 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-9.0.3
Removing intermediate container 56e2de370d2a
 ---> 97c0891618b8
Step 6/13 : RUN pip wheel --wheel-dir=/root/wheels -r /tmp/requirements.txt
 ---> Running in 90fad1309a74
Collecting aniso8601==1.2.1 (from -r /tmp/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/61/f3/74a5a8affb192863f5f6aa3dfb0059a97442ff683d44fcc842b509758129/aniso8601-1.2.1.tar.gz (62kB)
Collecting appdirs==1.4.3 (from -r /tmp/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
  Saved /root/wheels/appdirs-1.4.3-py2.py3-none-any.whl
Collecting argcomplete==1.9.2 (from -r /tmp/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/0f/ee/625763d848016115695942dba31a9937679a25622b6f529a2607d51bfbaa/argcomplete-1.9.2-py2.py3-none-any.whl
  Saved /root/wheels/argcomplete-1.9.2-py2.py3-none-any.whl
Collecting asn1crypto==0.24.0 (from -r /tmp/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
  Saved /root/wheels/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting base58==0.2.4 (from -r /tmp/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/58/a8/2bd2b3903264326c943d8526cd2700975d600a31566a04f0166258e73ead/base58-0.2.4-py3-none-any.whl
  Saved /root/wheels/base58-0.2.4-py3-none-any.whl
Collecting beautifulsoup4==4.6.0 (from -r /tmp/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
  Saved /root/wheels/beautifulsoup4-4.6.0-py3-none-any.whl
Collecting boto3==1.7.16 (from -r /tmp/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/4e/5d/19605225734850b9c7c859ab7142976542d2fb0a9a67245cd10cf6ed81c6/boto3-1.7.16-py2.py3-none-any.whl (128kB)
  Saved /root/wheels/boto3-1.7.16-py2.py3-none-any.whl
Collecting botocore==1.10.16 (from -r /tmp/requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/63/14/b570ca34ffe7008623cc22c51be973e1ac9b42ba91572026940f392bc333/botocore-1.10.16-py2.py3-none-any.whl (4.2MB)
  Saved /root/wheels/botocore-1.10.16-py2.py3-none-any.whl
Collecting certifi==2018.4.16 (from -r /tmp/requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
  Saved /root/wheels/certifi-2018.4.16-py2.py3-none-any.whl
Collecting cffi==1.10.0 (from -r /tmp/requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/5b/b9/790f8eafcdab455bcd3bd908161f802c9ce5adbf702a83aa7712fcc345b7/cffi-1.10.0.tar.gz (418kB)
Collecting cfn-flip==1.0.3 (from -r /tmp/requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/ba/c8/a928c55457441c87366eb2423efca9aa0f46380994fd8a476153493c319a/cfn_flip-1.0.3.tar.gz
Collecting chardet==3.0.4 (from -r /tmp/requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
  Saved /root/wheels/chardet-3.0.4-py2.py3-none-any.whl
Collecting click==6.7 (from -r /tmp/requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
  Saved /root/wheels/click-6.7-py2.py3-none-any.whl
Collecting cryptography==2.3.1 (from -r /tmp/requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/22/21/233e38f74188db94e8451ef6385754a98f3cad9b59bedf3a8e8b14988be4/cryptography-2.3.1.tar.gz (449kB)
Collecting decorator==4.1.2 (from -r /tmp/requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/a1/4e/c42167ba5c3192bed633726d39d7896cc55d4fa3ec4a1fb60cd3a53fc4c7/decorator-4.1.2-py2.py3-none-any.whl
  Saved /root/wheels/decorator-4.1.2-py2.py3-none-any.whl
Collecting docutils==0.14 (from -r /tmp/requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
  Saved /root/wheels/docutils-0.14-py3-none-any.whl
Collecting durationpy==0.5 (from -r /tmp/requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/24/85/70dabb62c3f9705566db0d8a33ebf6c203b5887a1a186f8bcf58a9bf46a6/durationpy-0.5.tar.gz
Collecting enum34==1.1.6 (from -r /tmp/requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
  Saved /root/wheels/enum34-1.1.6-py3-none-any.whl
Collecting Flask==0.12.2 (from -r /tmp/requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/77/32/e3597cb19ffffe724ad4bf0beca4153419918e7fa4ba6a34b04ee4da3371/Flask-0.12.2-py2.py3-none-any.whl (83kB)
  Saved /root/wheels/Flask-0.12.2-py2.py3-none-any.whl
Collecting Flask-Ask==0.9.8 (from -r /tmp/requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/6a/f5/d4709ae94584a0b1541e9b52b2d25a8a1bdb6e2da9d6870f23fdd0523a30/Flask-Ask-0.9.8.tar.gz (40kB)
Collecting funcsigs==1.0.2 (from -r /tmp/requirements.txt (line 21))
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
  Saved /root/wheels/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting future==0.16.0 (from -r /tmp/requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
Collecting fuzzywuzzy==0.15.1 (from -r /tmp/requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/d4/b9/2f883a23ca6a843cbd25e3ac9d625de4fecf830c4a08979a528b1a3354a8/fuzzywuzzy-0.15.1-py2.py3-none-any.whl
  Saved /root/wheels/fuzzywuzzy-0.15.1-py2.py3-none-any.whl
Collecting gmusicapi==10.1.2 (from -r /tmp/requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/44/44/fe21b95528cabcb7fbbe79860d650b00b615b12ae4e54c2ed3c2cc86e9cd/gmusicapi-10.1.2.tar.gz (166kB)
Collecting gpsoauth==0.4.1 (from -r /tmp/requirements.txt (line 25))
  Downloading https://files.pythonhosted.org/packages/96/a1/2b366c602ee081def4dd80624581dfa8eb23d20c5a51f8a2591c40fa8d41/gpsoauth-0.4.1.tar.gz
Collecting hjson==3.0.1 (from -r /tmp/requirements.txt (line 26))
  Downloading https://files.pythonhosted.org/packages/8a/92/6b6b85064f8a88cb3b31901d839e7b45c33e4ee450bb1b3cf0c226cca8ec/hjson-3.0.1.tar.gz (43kB)
Collecting httplib2==0.10.3 (from -r /tmp/requirements.txt (line 27))
  Downloading https://files.pythonhosted.org/packages/e4/2e/a7e27d2c36076efeb8c0e519758968b20389adf57a9ce3af139891af2696/httplib2-0.10.3.tar.gz (204kB)
Collecting idna==2.5 (from -r /tmp/requirements.txt (line 28))
  Downloading https://files.pythonhosted.org/packages/11/7d/9bbbd7bb35f34b0169542487d2a8859e44306bb2e6a4455d491800a5621f/idna-2.5-py2.py3-none-any.whl (55kB)
  Saved /root/wheels/idna-2.5-py2.py3-none-any.whl
Collecting ipaddress==1.0.18 (from -r /tmp/requirements.txt (line 29))
  Downloading https://files.pythonhosted.org/packages/4e/13/774faf38b445d0b3a844b65747175b2e0500164b7c28d78e34987a5bfe06/ipaddress-1.0.18.tar.gz
Collecting itsdangerous==0.24 (from -r /tmp/requirements.txt (line 30))
  Downloading https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
Collecting Jinja2==2.9.6 (from -r /tmp/requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/5e/73/10c45b82a88ed6b7751bd40da31eeefd7b362e07b56a99aa6e56655a0794/Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
  Saved /root/wheels/Jinja2-2.9.6-py2.py3-none-any.whl
Collecting jmespath==0.9.3 (from -r /tmp/requirements.txt (line 32))
  Downloading https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
  Saved /root/wheels/jmespath-0.9.3-py2.py3-none-any.whl
Collecting kappa==0.6.0 (from -r /tmp/requirements.txt (line 33))
  Downloading https://files.pythonhosted.org/packages/ee/fa/1b8328d2199520ef5a257f8a2e9315ed0b0194e353a152ca1959490dfbc8/kappa-0.6.0.tar.gz
Collecting lambda-packages==0.19.0 (from -r /tmp/requirements.txt (line 34))
  Downloading https://files.pythonhosted.org/packages/e5/52/fb693a38c1cac26e03f67cd16e9eb32dbe3852d444885d0c869be33ad9e1/lambda_packages-0.19.0.tar.gz (74.1MB)
The command '/bin/sh -c pip wheel --wheel-dir=/root/wheels -r /tmp/requirements.txt' returned a non-zero code: 137
```

**Comment by leer10** [comment]
I'm encountering the same issue

**Comment by leer10** [comment]
FYI I read that error code 137 is from low memory. I worked around by stopping some services on my device while it was being built. I encountered another error, but I fixed it by changing the references to "python:3.7.5-alpine" in the Dockerfile
