### ISSUE TITLE
Can't get Heroku to run

### ISSUE THREAD

**Issue by mbibbey** [stevenleeg/geemusic#56]
I can't get the Heroku app to run without crashing. My log is below. It looks like it is a problem with the google account login, but I have edited and checked it multiple times in the Heroku Config Variables.

I don't have 2-step verification turned on on the google account, so just using my normal login credentials.

Any ideas?

2017-01-30T19:47:52.182937+00:00 heroku[web.1]: Starting process with command `python server.py`
2017-01-30T19:47:55.801681+00:00 app[web.1]: /app/.heroku/python/lib/python2.7/site-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
2017-01-30T19:47:55.801701+00:00 app[web.1]:   _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
2017-01-30T19:47:56.080598+00:00 app[web.1]: Traceback (most recent call last):
2017-01-30T19:47:56.080611+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-01-30T19:47:56.080612+00:00 app[web.1]:     from geemusic import app
2017-01-30T19:47:56.080613+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 10, in <module>
2017-01-30T19:47:56.086875+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)
2017-01-30T19:47:56.086901+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 129, in generate_api
2017-01-30T19:47:56.086953+00:00 app[web.1]:     return cls(environ['GOOGLE_EMAIL'], environ['GOOGLE_PASSWORD'], **kwargs)
2017-01-30T19:47:56.086976+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 13, in __init__
2017-01-30T19:47:56.087299+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")
2017-01-30T19:47:56.087330+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!
2017-01-30T19:47:56.364819+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-30T19:47:56.348554+00:00 heroku[web.1]: Process exited with status 1

**Comment by mbibbey** [comment]
Needed to reset my google password.
