### ISSUE TITLE
OSError: a valid MAC could not be determined.

### ISSUE THREAD

**Issue by joemarshalljm** [stevenleeg/geemusic#65]
I get this error:

OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).

and I'm not sure what to do!

**Comment by PostsDesert** [comment]
Do you have the full log? It would help a lot to see where the error is coming from.

**Comment by apsco** [comment]
I have the same issue.....
Running this on a VPS. Here is the log I got: 

Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from geemusic import app
  File "/home/geemusic/geemusic/geemusic/__init__.py", line 13, in <module>
    api = GMusicWrapper.generate_api(logger=app.logger)
  File "/home/geemusic/geemusic/geemusic/utils/music.py", line 247, in generate_api
    **kwargs)
  File "/home/geemusic/geemusic/geemusic/utils/music.py", line 13, in __init__
    success = self._api.login(username, password, environ.get('ANDROID_ID', Mobileclient.FROM_MAC_ADDRESS))
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/mobileclient.py", line 115, in login
    raise OSError("a valid MAC could not be determined."
OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).

**Comment by stevenleeg** [comment]
Hmm, this is weird. It sounds like python is having trouble getting a MAC address from the machine. You might be able to solve this by setting `ANDROID_ID=[some random string]` in your `.env` file. Could you try that and see if it fixes the issue?

**Comment by stevenleeg** [comment]
Closing this due to inactivity. Let me know if you're still having issues.
