### ISSUE TITLE
[Errno 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ruricu** [stevenleeg/geemusic#73]
I'm attempting to use geemusic routed through my own domain, and fundamentally, it works. I am able to stream music for some amount of time, but within 1-3 tracks, the stream dies with the following error:

```
127.0.0.1 - - [01/Mar/2017 09:10:53] "GET /geemusic/stream/Tbfdgorvksltrctbfj6ritwyw3a HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42264)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 279, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "C:\Python27\lib\ssl.py", line 701, in sendall
    v = self.send(data[count:])
  File "C:\Python27\lib\ssl.py", line 667, in send
    v = self._sslobj.write(data)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
{
  "context": {
    "AudioPlayer": {
      "offsetInMilliseconds": 0,
      "playerActivity": "PLAYING",
      "token": "56826"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.XXX"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "user": {
        "userId": "amzn1.ask.account.XXX
      }
    }
  },
  "request": {
    "currentPlaybackState": {
      "offsetInMilliseconds": 0,
      "playerActivity": "PLAYING",
      "token": "56826"
    },
    "error": {
      "message": "Request timed out",
      "type": "MEDIA_ERROR_SERVICE_UNAVAILABLE"
    },
    "locale": "en-US",
    "requestId": "amzn1.echo-api.request.XXX",

    "timestamp": "2017-03-01T14:10:45Z",
    "token": "84360",
    "type": "AudioPlayer.PlaybackFailed"
  },
  "version": "1.0"
}
{
  "offsetInMilliseconds": 0,
  "playerActivity": "PLAYING",
  "token": "56826",
  "url": "https://[domain]/geemusic/stream/Twardvumg2vb3mtjbbkx3sjnluu"
}
```
This doesn't kill the server immediately, but is followed by something like:
```
127.0.0.1 - - [01/Mar/2017 09:36:47] "GET /geemusic/stream/Txvh7bappfxqbd5knqhakeidl7y HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55772)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 279, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "C:\Python27\lib\ssl.py", line 701, in sendall
    v = self.send(data[count:])
  File "C:\Python27\lib\ssl.py", line 667, in send
    v = self._sslobj.write(data)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
{
  "context": {
    "AudioPlayer": {
      "offsetInMilliseconds": 45550,
      "playerActivity": "STOPPED",
      "token": "26018"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.XXX"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "user": {
        "userId": "amzn1.ask.account.XXX"
      }
    }
  },
  "request": {
    "locale": "en-US",
    "offsetInMilliseconds": 45550,
    "requestId": "amzn1.echo-api.request.XXX",

    "timestamp": "2017-03-01T14:36:41Z",
    "token": "26018",
    "type": "AudioPlayer.PlaybackStopped"
  },
  "version": "1.0"
}
{
  "offsetInMilliseconds": 45550,
  "playerActivity": "STOPPED",
  "token": "26018",
  "url": "https://vcr.host/geemusic/stream/Tbfdgorvksltrctbfj6ritwyw3a"
}
--------------------------------------------------------------------------------

DEBUG in playback [C:\GitHub\GeeMusic2\geemusic\intents\playback.py:12]:
Stopped at 45550
--------------------------------------------------------------------------------

127.0.0.1 - - [01/Mar/2017 09:36:49] "POST /geemusic HTTP/1.1" 400 -
{
  "context": {
    "AudioPlayer": {
      "offsetInMilliseconds": 45550,
      "playerActivity": "STOPPED",
      "token": "26018"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.XXX"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "user": {
        "userId": "amzn1.ask.account.XXX"
      }
    }
  },
  "request": {
    "currentPlaybackState": {
      "offsetInMilliseconds": 45550,
      "playerActivity": "STOPPED",
      "token": "26018"
    },
    "error": {
      "message": "Seek call failed!, Response Code:200",
      "type": "MEDIA_ERROR_INVALID_REQUEST"
    },
    "locale": "en-US",
    "requestId": "amzn1.echo-api.request.XXX",

    "timestamp": "2017-03-01T14:36:43Z",
    "token": "26018",
    "type": "AudioPlayer.PlaybackFailed"
  },
  "version": "1.0"
}
{
  "offsetInMilliseconds": 45550,
  "playerActivity": "STOPPED",
  "token": "26018",
  "url": "https://[domain]/geemusic/stream/Tbfdgorvksltrctbfj6ritwyw3a"
}
127.0.0.1 - - [01/Mar/2017 09:36:50] "POST /geemusic HTTP/1.1" 400 -
```

To my understanding, @PostsDesert 's PR breaks the stream into chunks like so:

``return Response(stream_with_context(req.iter_content(chunk_size=1024 * 1024)), content_type=req.headers['content-type'])``

but it appears that occasionally, one of these chunks fails to stream. I've played with reducing and increasing the chunk size, but neither seem to prevent the failure from occurring.
I don't see anything in my Apache logs that would indicate an error coming from that end. Any ideas?

**Comment by ruricu** [comment]
I may have found a hint while poking around this topic further. The GMusicProxy project (https://github.com/diraimondo/gmusicproxy) also uses the gmusicapi, but he notes that:

"My project is based on the great Unofficial Google Play Music API of Simon Weber: it already permits to create URLs to stream the tracks as regular MP3 but they expire in 1 minute! Keeping this proxy running, it can generate persistent local URLs that never expire and that can be used in any media-player."

@stevenleeg When exactly does GeeMusic request the next url to stream? It appears that in some cases, this could be happening prematurely, allowing the proxy to expire before they are consumed, and resulting in the timeout that kills the service.

Is this possible? Additionally, would it be possible to leverage this GMusicProxy project to create "persistant local URLs"?

**Comment by PostsDesert** [comment]
I haven't used geemusic in awhile, but gmusicproxy sounds like it could solve the issue of chunks dropping on longer songs. I'll see if I can reproduce the issue and also look into gmusicproxy. 

On the request issue, geemusic requests the song right before sending the data off to Amazon so there's not much improvement to be had there.

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
