### ISSUE TITLE
Error starting Foreman

### ISSUE THREAD

**Issue by ryanneve** [stevenleeg/geemusic#80]
I'm sure it's something simple, but following your instructions I have this problem:

```
(.venv) pi@raspberrypi:~/Development$ foreman start
ERROR: Procfile does not exist.

```
This is a brand new raspbian install with nothing else installed.

**Comment by ryanneve** [comment]
I thought perhaps the current directory was the problem, so I tried:
```
(.venv) pi@raspberrypi:~/Development/geemusic$ foreman start
18:33:39 web.1  | started with pid 3637
18:33:40 web.1  | Traceback (most recent call last):
18:33:40 web.1  |   File "server.py", line 1, in <module>
18:33:40 web.1  |     from geemusic import app
18:33:40 web.1  |   File "/home/pi/Development/geemusic/geemusic/__init__.py", line 3, in <module>
18:33:40 web.1  |     from flask_ask import Ask
18:33:40 web.1  | ImportError: No module named 'flask_ask'
18:33:40 web.1  | exited with code 1
18:33:40 system | sending SIGTERM to all processes
```

**Comment by ryanneve** [comment]
my fault. .env was in wrong directory.
