### ISSUE TITLE
ImportError: No module named 'flask.debughelpers'

### ISSUE THREAD

**Issue by phlepper** [stevenleeg/geemusic#82]
I'm getting the following error after setting up geemusic.  Sometimes it works and plays my music, but other times, I get the following output.  Is there something I need to do to add flask.debughelpers so I can see what the problem is?

```
192.xxx.xxx.xxx - - [13/Apr/2017 22:43:46] "POST /alexa HTTP/1.1" 500 - Traceback (most recent call last):
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
  File "/home/x/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
  File "/home/x/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/home/x/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/x/.local/lib/python3.5/site-packages/flask_ask/core.py", line 530, in _flask_view_func
  File "/home/x/.local/lib/python3.5/site-packages/flask_ask/core.py", line 480, in _alexa_request
  File "/home/x/.local/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
  File "/home/x/.local/lib/python3.5/site-packages/werkzeug/utils.py", line 73, in __get__
  File "/home/x/.local/lib/python3.5/site-packages/werkzeug/wrappers.py", line 446, in data
  File "/home/x/.local/lib/python3.5/site-packages/werkzeug/wrappers.py", line 476, in get_data
  File "/home/x/.local/lib/python3.5/site-packages/flask/wrappers.py", line 192, in _load_form_data

ImportError: No module named 'flask.debughelpers'
192.xxx.xxx.xxx - - [13/Apr/2017 22:43:46] "POST /alexa HTTP/1.1" 500 -
```

Thanks!
Paul

**Comment by PostsDesert** [comment]
Have you tried reinstalling your pip modules?
`pip3 install -r requirements.txt`

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
