### ISSUE TITLE
raise Exception("Unsuccessful login. Aborting!")

### ISSUE THREAD

**Issue by arimk** [stevenleeg/geemusic#83]
I have those logs on heroku. Did not change a thing on my account on google, and i did not change anything on the code. Worked in march.
```
2017-04-16T08:42:22.187730+00:00 heroku[web.1]: Starting process with command python3 server.py
2017-04-16T08:42:24.957526+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)

2017-04-16T08:42:24.957544+00:00 app[web.1]:   _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)

2017-04-16T08:42:25.463000+00:00 app[web.1]: Traceback (most recent call last):

2017-04-16T08:42:25.463018+00:00 app[web.1]:   File "server.py", line 1, in <module>

2017-04-16T08:42:25.463195+00:00 app[web.1]:     from geemusic import app

2017-04-16T08:42:25.463198+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 13, in <module>

2017-04-16T08:42:25.463337+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)

2017-04-16T08:42:25.463338+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 247, in generate_api

2017-04-16T08:42:25.463570+00:00 app[web.1]:     **kwargs)

2017-04-16T08:42:25.463572+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 16, in __init__

**2017-04-16T08:42:25.463696+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")**

2017-04-16T08:42:25.463712+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!

2017-04-16T08:42:25.631067+00:00 heroku[web.1]: State changed from starting to crashed

2017-04-16T08:42:25.614274+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by arimk** [comment]
Just received an email saying someone has my password, and it was blocked. So that was it probably...

**Comment by arimk** [comment]
Yes it was this...
