### ISSUE TITLE
Unable to play playlists

### ISSUE THREAD

**Issue by snapperheadjoe** [stevenleeg/geemusic#84]
I setup a new Gee music instance using the Heroku walkthrough.  Quick shoutout to Steven for the awesome walkthrough.

I have the free Gmusic account (14k+ songs uploaded) so I knew I wouldn't be able to play individual songs however I discovered if I say "Alexa, ask gee music to start playlist Sting"  it will play whatever playlist I have in my library.  This was working great till around midnight last night.  I stopped a playlist to start another one and since then the Echo lights spin and I get the message "The skill took too long to respond".  I haven't made any changes other than adding additional playlist to my library.  I was able to play all of my new and old playlists until around midnight then the error started.  

Testing the Skill on Amazon returns "The remote endpoint could not be called, or the response it returned was invalid." but only if I try to start a playlist.  If I send it any other gee music command it responds with the typical "I can't find that artist, album, song, etc."  The playlist intent generates the previous error.

Any help you can provide to get my playlists working again would be great.  I'm wodering if some code change was introduced after midnight April 17 that might have caused the playlist playback to suddenly stop working.

**Echo Dot heroku logs.  Using phrase "Gee music start sting playlist".:**
2017-04-17T16:57:56.650853+00:00 app[web.1]: DEBUG in music [/app/geemusic/utils/music.py:235]:
2017-04-17T16:57:56.650855+00:00 app[web.1]: The top scoring match was: {'index': 11, 'name': 'sting', 'score': 100}
2017-04-17T16:57:56.650858+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-17T16:57:56.663545+00:00 app[web.1]: 10.167.190.210 - - [17/Apr/2017 16:57:56] "POST /alexa HTTP/1.1" 500 -
2017-04-17T16:57:56.663886+00:00 app[web.1]: Traceback (most recent call last):
2017-04-17T16:57:56.663888+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
2017-04-17T16:57:56.663889+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2017-04-17T16:57:56.663889+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
2017-04-17T16:57:56.663890+00:00 app[web.1]:     response = self.handle_exception(e)
2017-04-17T16:57:56.663891+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
2017-04-17T16:57:56.663892+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-04-17T16:57:56.663892+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-04-17T16:57:56.663894+00:00 app[web.1]:     raise value
2017-04-17T16:57:56.663895+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-04-17T16:57:56.663895+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-04-17T16:57:56.663896+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-04-17T16:57:56.663897+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-04-17T16:57:56.663897+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-04-17T16:57:56.663898+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-04-17T16:57:56.663898+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-04-17T16:57:56.663899+00:00 app[web.1]:     raise value
2017-04-17T16:57:56.663900+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-04-17T16:57:56.663900+00:00 app[web.1]:     rv = self.dispatch_request()
2017-04-17T16:57:56.663901+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-04-17T16:57:56.663902+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-04-17T16:57:56.663902+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 560, in _flask_view_func
2017-04-17T16:57:56.663903+00:00 app[web.1]:     result = self._map_intent_to_view_func(self.request.intent)()
2017-04-17T16:57:56.663904+00:00 app[web.1]:   File "/app/geemusic/intents/selection.py", line 149, in play_playlist
2017-04-17T16:57:56.663904+00:00 app[web.1]:     thumbnail = api.get_thumbnail(queue.current_track()['albumArtRef'][0]['url'])
2017-04-17T16:57:56.663905+00:00 app[web.1]: KeyError: 'albumArtRef'
2017-04-17T16:57:56.704266+00:00 app[web.1]: 10.178.64.67 - - [17/Apr/2017 16:57:56] "POST /alexa HTTP/1.1" 200 -
2017-04-17T16:57:56.705379+00:00 heroku[router]: at=info method=POST path="/alexa" host=enigmatic-woodland-84749.herokuapp.com request_id=5112f891-db07-4b0c-9b54-d6471c688e31 fwd="72.21.217.160" dyno=web.1 connect=1ms service=3288ms status=200 bytes=154 protocol=https

**Amazon dashboard test skil  heroku logs.  Using text "start playlist sting":**
2017-04-17T16:47:25.762977+00:00 app[web.1]: DEBUG in music [/app/geemusic/utils/music.py:235]:
2017-04-17T16:47:25.762979+00:00 app[web.1]: The top scoring match was: {'index': 11, 'name': 'sting', 'score': 67}
2017-04-17T16:47:25.762983+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-17T16:47:25.767935+00:00 app[web.1]: 10.41.215.197 - - [17/Apr/2017 16:47:25] "POST /alexa HTTP/1.1" 200 -
2017-04-17T16:47:25.790991+00:00 app[web.1]: 10.171.127.156 - - [17/Apr/2017 16:47:25] "POST /alexa HTTP/1.1" 200 -
2017-04-17T16:54:39.530257+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=POST path="/alexa" host=enigmatic-woodland-84749.herokuapp.com request_id=54d6446c-afd3-41ec-8f31-8e9394888ba4 fwd="72.21.217.178" dyno=web.1 connect=0ms service=11875ms status=499 bytes= protocol=https
2017-04-17T16:54:39.510410+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-17T16:54:39.510434+00:00 app[web.1]: DEBUG in music [/app/geemusic/utils/music.py:215]:
2017-04-17T16:54:39.510435+00:00 app[web.1]: The artist name is
2017-04-17T16:54:39.510471+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-17T16:54:39.511164+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-17T16:54:39.511165+00:00 app[web.1]: DEBUG in music [/app/geemusic/utils/music.py:235]:
2017-04-17T16:54:39.511192+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-17T16:54:39.511166+00:00 app[web.1]: The top scoring match was: {'index': 11, 'name': 'sting', 'score': 100}
2017-04-17T16:54:39.524653+00:00 app[web.1]: 10.167.67.198 - - [17/Apr/2017 16:54:39] "POST /alexa HTTP/1.1" 500 -
2017-04-17T16:54:39.525172+00:00 app[web.1]: Traceback (most recent call last):
2017-04-17T16:54:39.525174+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
2017-04-17T16:54:39.525175+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2017-04-17T16:54:39.525176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
2017-04-17T16:54:39.525176+00:00 app[web.1]:     response = self.handle_exception(e)
2017-04-17T16:54:39.525177+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
2017-04-17T16:54:39.525178+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-04-17T16:54:39.525179+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-04-17T16:54:39.525180+00:00 app[web.1]:     raise value
2017-04-17T16:54:39.525181+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-04-17T16:54:39.525181+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-04-17T16:54:39.525182+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-04-17T16:54:39.525183+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-04-17T16:54:39.525183+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-04-17T16:54:39.525184+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-04-17T16:54:39.525185+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-04-17T16:54:39.525185+00:00 app[web.1]:     raise value
2017-04-17T16:54:39.525186+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-04-17T16:54:39.525187+00:00 app[web.1]:     rv = self.dispatch_request()
2017-04-17T16:54:39.525187+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-04-17T16:54:39.525188+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-04-17T16:54:39.525188+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_ask/core.py", line 560, in _flask_view_func
2017-04-17T16:54:39.525189+00:00 app[web.1]:     result = self._map_intent_to_view_func(self.request.intent)()
2017-04-17T16:54:39.525190+00:00 app[web.1]:   File "/app/geemusic/intents/selection.py", line 149, in play_playlist
2017-04-17T16:54:39.525190+00:00 app[web.1]:     thumbnail = api.get_thumbnail(queue.current_track()['albumArtRef'][0]['url'])
2017-04-17T16:54:39.525192+00:00 app[web.1]: KeyError: 'albumArtRef'

**Comment by snapperheadjoe** [comment]
Just got off a chat with Google Play support and they confirmed that the Google Home speaker will only allow you to play music from personal playlists if you have a free account, no direct album or track streaming.  I'm wondering if their API is able to determine that my requests are coming from a Heroku instance rather than a Google Home speaker and have simply stopped responding to my requests.  Its very annoying because I listened to seveal hours of music from playlists until it just stopped working.

**Comment by deviprasad97** [comment]
I have a paid Google Play Music account but still, when I ask to play a playlist Alexa says there was an error with requested skill response

**Comment by whyrv** [comment]
I got the same response even though I am not using heroku but rather my own server.

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.

**Comment by snapperheadjoe** [comment]
I'd like to open this issue again.  I recently created a new Geemusic app for my Alexa now that Amazon no longer supports uploaded music.  I am able to play individual songs, albums and artists from my uploaded Google play library.  Ironically I am unable to play any playlists which was supposed to be the only thing that the free google play accounts were able to play.  I'm not sure why playlists do not work but everything else works flawlessly.  When requesting any playlist the Alexa will do the blue spin for some time and eventually return "The requested skill did not provide a valid response".  I can request any song, album or artist and it starts playing the music immediately.

**Comment by snapperheadjoe** [comment]
Further info.  When I ask it to play all my music it responds that its playing my "Playing I'm Feeling Lucky Radio." playlist then nothing happens.

"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "Playing music from your personalized station."
			},
			"card": {
				"type": "Standard",
				"title": "Playing I'm Feeling Lucky Radio.",
				"text": "",
				"image": {
					"smallImageUrl": "https://i.imgur.com/NYTSqHZ.png",
					"largeImageUrl": "https://i.imgur.com/NYTSqHZ.png"
				}
			},
			"directives": [
				{
					"type": "AudioPlayer.Play",
					"playBehavior": "REPLACE_ALL",
					"audioItem": {
						"stream": {
							"token": "d88ff859-7d82-4440-91a3-aba681f58066",
							"url": "https://xxxxgeemusic.herokuapp.com/alexa/stream/None",
							"offsetInMilliseconds": 0
						}
					}
				}
			],
			"shouldEndSession": true,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {}
